### ISSUE TITLE
Photo with caption

### ISSUE THREAD

**Issue by mr-deamon** [edisonchee/slimbot#1]
Is it possible that photos with a caption are not received by slimbot?

**Comment by edisonchee** [comment]
Hi @mr-deamon! Slimbot should be able to receive them without any issues. Are you experiencing any difficulty with sending files to your bot?

Can you provide a snippet of code to reproduce the error?

**Comment by edisonchee** [comment]
Hi @mr-deamon, I tried to reproduce the error but was unable to. Let me know if you're still facing any problems with the lib! I'll close this issue for now.

**Comment by panzad3** [comment]
hello so I have a problem of sending caption with sendPhoto method - my code:
slimbot.sendPhoto("chatID","photoID" , caption = "TEST", 
disable_notification = false).then(message => {
console.log(message.result);
 });

but pictures arrive in plain format with no captions, Ty
