### ISSUE TITLE
optionalParams  in sendPhoto

### ISSUE THREAD

**Issue by devjet** [edisonchee/slimbot#10]
Hi there
How to use optionalParams with sending(uploading) photos, for examle I need  _disable_notification_: **true**
but when I use like this:
```
 let optionalParams = {
        disable_notification: true
    };

    slimbot.sendPhoto(TELEGRAM_CHAT_NAME, fileUpload,optionalParams)
```
It's not working
thanks

**Comment by edisonchee** [comment]
Hi @devjet, what is the error you got?

**Comment by edisonchee** [comment]
@devjet, also check if using chat_id works. That's how the method should work e.g.

```slimbot.sendPhoto(CHAT_ID, fileUpload, optionalParams)```

[You can refer to the API here](https://core.telegram.org/bots/api#sendphoto).

**Comment by edisonchee** [comment]
Closed due to inactivity.
