### ISSUE TITLE
request-promise@4.2.2 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself

### ISSUE THREAD

**Issue by valVk** [edisonchee/slimbot#13]
I think that `request` has to be listed in dependencies explicitly as this is required package

**Comment by edisonchee** [comment]
Good catch. Will add it in the next release. Thanks!

**Comment by papajo** [comment]
has this issue been fixed? just ran into this...
// ♥ npm install request-promise --save
npm WARN request-promise@4.2.2 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN blockchain@1.0.0 No repository field.

+ request-promise@4.2.2
updated 1 package in 6.131s

**Comment by valVk** [comment]
Looks like it was
https://github.com/edisonchee/slimbot/blob/master/package.json#L29-L30
