### ISSUE TITLE
typo in WIKI documentation setWebhook

### ISSUE THREAD

**Issue by valVk** [edisonchee/slimbot#14]
Typo in [WIKI](https://github.com/edisonchee/slimbot/wiki#webhook)

`slimbot.setWebhook('https://www.example.com/bot_updates');`
has to be changed to 
`slimbot.setWebhook({ url: 'https://www.example.com/bot_updates' });`

**Comment by edisonchee** [comment]
Good catch again. I've updated the Wiki. Thanks for your help!
