### ISSUE TITLE
Uploading a file to Telegram's servers

### ISSUE THREAD

**Issue by suntong** [edisonchee/slimbot#16]
At
https://github.com/edisonchee/slimbot/blob/ac19b1fa6f14793cf64fa97a403656835269339b/examples/sendFile.js#L26

The `inputFile` was not defined before used. Can I use the code as-is, or there are some magic behind the scene? 

Thx!

**Comment by edisonchee** [comment]
Hi @suntong, apologies for the mistake in the example. That line should be:

```slimbot.sendPhoto(message.chat.id, fileUpload).then(message => { ```

```fileUpload``` was defined earlier in line 10, where we created a readable stream using ```fs```.
https://github.com/edisonchee/slimbot/blob/ac19b1fa6f14793cf64fa97a403656835269339b/examples/sendFile.js#L10

Telegram Bot API requires file uploads to be sent as a POST request with multipart/form-data. If you dig into the [slimbot source](https://github.com/edisonchee/slimbot/blob/ac19b1fa6f14793cf64fa97a403656835269339b/src/telegram.js), you will see how POST requests are made:

https://github.com/edisonchee/slimbot/blob/ac19b1fa6f14793cf64fa97a403656835269339b/src/telegram.js#L40

which is taking care of by the underlying [Request](https://www.npmjs.com/package/request#multipartform-data-multipart-form-uploads) library we're using.

I'll amend the example and do a quick update. Thanks for catching this!

**Comment by edisonchee** [comment]
Aaaand done! Fixed in 542e25a 

Do you still have any issues with the library?

**Comment by suntong** [comment]
Oh, thanks a lot @edisonchee, I'll give it a try, and let you know if there is any remaining issues, or just close this. Thx again.
