### ISSUE TITLE
How to detect bot's own messages

### ISSUE THREAD

**Issue by suntong** [edisonchee/slimbot#20]
Hi, 

I've allowed my bot to receive/access Telegram Group messages. So now I need to worry it should not be responding to its own messages, which'll cause looping. 

What's the best way to tell if a message is of its own? Thx.

**Comment by rubdevton** [comment]
You do not have to worry about this; the bot does not receive updates for its own messages.

**Comment by suntong** [comment]
Even after I've allowed my bot to receive all Telegram Group messages? 
That's not enabled by default. 

I.e., I want to know which party guarantees that bot does not receive its own messages, because the for other chatting platform I'm also working on, it's a big thing.

**Comment by rubdevton** [comment]
If we're talking about the same feature, all that option does is allow you to receive messages other than commands directed to your bots. It does not actually do anything towards receiving your own bots' messages.

Preventing your own messages from being received as updates is handled on Telegram's side. They do not create a new update object for your own messages, so for you it's as if it never actually happened.

**Comment by suntong** [comment]
Oh, great, thanks a lot for spending time explaining all this. Have a nice day!
