### ISSUE TITLE
[QUESTION] How can I listen for a specific command ?

### ISSUE THREAD

**Issue by sinout** [edisonchee/slimbot#22]
E.g how can I listen for `/start` command ? 
Is this available only by parsing message `text` property or by `entities[0].type` ?

**Comment by edisonchee** [comment]
Hi @sinout, you can do this:
```js
slimbot.on('message', message => {
  if (message.text === '/start') {
    // do your thing here when someone uses the /start command
  }
});
```

**Comment by sinout** [comment]
Yeah, thank you. Just wanted to know if there are any predefined listeners for commands.
