### ISSUE TITLE
Make the SlimBot plugin based

### ISSUE THREAD

**Issue by mehranrasoli** [edisonchee/slimbot#26]
Hey @edisonchee !
It will be awesome if you plan to implement a way to write some useful plugins for the but, like what [Telebot](https://github.com/mullwar/telebot/tree/master/plugins) is doing, but not so complex and buggy!

Awesome botgram!

**Comment by edisonchee** [comment]
hello @mehrunrasoli, thank you for your compliments!

I've not thought about adding a plugin system for fear of bloating up its core functionality. If there are a lot of requests for it, we can work on it together. :)
