### ISSUE TITLE
Add Ability to Stop Polling

### ISSUE THREAD

**Issue by vigoren** [edisonchee/slimbot#29]
I was wondering if it would be possible to add a stopPolling function to the bot. I have a situation where I would like to have the bot stop receiving updates from telegram without having to terminate the current process.

**Comment by edisonchee** [comment]
I'll look into it! Thanks for the suggestion. Also, sorry for replying late; I was away on holiday for a couple of weeks.

**Comment by vigoren** [comment]
No worries and thanks for looking into it!

**Comment by edisonchee** [comment]
@vigoren This took forever but... finally [added it into the library](https://github.com/edisonchee/slimbot/releases/tag/4.3.1).
