### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by elisaado** [edisonchee/slimbot#3]
I'm really interested in this project, I wrote a basic bot in it, but I want to do more! Guys, please! Where are the docs? Only the `readme.md` has some info, but it's not enough to build (let's say) an inline bot

**Comment by edisonchee** [comment]
Hi @elisaado, good catch in the readme! I've merged your PR onto the master branch already.

Do you mean you'd like to see some examples on how to build an inline bot?

**Comment by elisaado** [comment]
Yeah that would also make everything clear

**Comment by edisonchee** [comment]
I'll try to flesh out the lib with more examples. Feel free to add your own if you have any, just make a PR.

**Comment by elisaado** [comment]
Alright!

**Comment by edisonchee** [comment]
Hi @elisaado, I've written a couple of examples to demonstrate using inline methods. Take a look and let me know if they are easy to understand.

[https://github.com/edisonchee/slimbot/tree/master/examples](https://github.com/edisonchee/slimbot/tree/master/examples)

**Comment by edisonchee** [comment]
Closed due to inactivity.

**Comment by elisaado** [comment]
Alright! I saw the examples, They're easy to read too. Good work!

### Btw, sorry for the inactiveness, vacation :stuck_out_tongue_closed_eyes:
