### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by suntong** [edisonchee/slimbot#30]
I'm getting the following exception from time to time:

```
Unhandled rejection Error: 400:
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}
    at Request.then.resp (/path/to/node_modules/slimbot/src/telegram.js:61:15)
```

which comes from here:

https://github.com/edisonchee/slimbot/blob/fea0d25b846c3f026a6741a264bca37eb0a2a59c/src/telegram.js#L58-L62

Would it be possible to provide as many relevant info as possible in the exception please? 

The async chatting nature has made my effort trying to capture and understand the condition when would such exception happen fruitless so far. 

thx!

**Comment by suntong** [comment]
I figured it out.

**Comment by edisonchee** [comment]
Hey @suntong, could you also share how you figured it out? All I'm doing in that exception is to grab Telegram Bot API's response. I did not do any extra processing on the client side since they're doing a great job on their documentation so far.

**Comment by suntong** [comment]
That `Bad Request: chat not found` error, for me, was not chat not found but actually because I forgot to put my bot into the group that it is posting to. 

I don't know JS well enough to make any code changes, but adding the bot in solved my problem. So I'm happy. :)

**Comment by edisonchee** [comment]
I'm glad you were able to solve the problem. Good job!
