### ISSUE TITLE
bot died in 20 seconds

### ISSUE THREAD

**Issue by suntong** [edisonchee/slimbot#36]
Hi, 

Please take a look at this [simpleUsage.js](https://gist.github.com/suntong/c6f732d0aba128723648f30f98084606) copied from https://github.com/edisonchee/slimbot/blob/master/examples/simpleUsage.js, just without `slimbot.stopPolling`.

However, it will die in 20 seconds:

```
$ time node simpleUsage.js 
polling...

real    0m20.915s
user    0m0.335s
sys     0m0.041s
```

I was expecting that the bot stay listening as long as I don't kill it.

**Comment by suntong** [comment]
This basically means that the module is unusable.  
Switching https://github.com/yagop/node-telegram-bot-api and am very happy now. 

Feel free to close it or fix it...

**Comment by ohenley** [comment]
@suntong Thx for refering of a working repo... this will be my third try.

**Comment by edisonchee** [comment]
Can't replicate the issue on my end. Tested on Node versions `10.16.0`, `12.10.0` and `13.8.0`. Without further information I can't help you debug.

Closed till more people have similar issues.

**Comment by qelphybox** [comment]
@edisonchee thx, i had the same problem, update to `13.8.0` helped

**Comment by paskausks** [comment]
This issue was encountered on v12.14.0, but an update to v12.18.2 seemed to fix it. Very interesting what the cause is.
