### ISSUE TITLE
Sending Photo Files from readable stream

### ISSUE THREAD

**Issue by suntong** [edisonchee/slimbot#37]
Following up on #28, 

> Send methods now make requests with formData if the file you're using is a readable stream.
> sendFile no longer broken; let me know if you have any issues using it.

I tried it but am still unable to make it works. 

```
    let fileUpload = fs.createReadStream(fn);
    slimbot.sendPhoto(message.chat.id, fileUpload).then(message => {
      console.log(message.result.photo);
```

The above is my code, and it is not working. 
Would you give a full working example please? Thx

**Comment by suntong** [comment]
Switching to https://github.com/yagop/node-telegram-bot-api and am very happy now.

Feel free to close it or fix it...

**Comment by edisonchee** [comment]
Again, can't replicate. You need to provide more details beyond "unable to make it work", like a stack trace.
