### ISSUE TITLE
Helper for reply_markup

### ISSUE THREAD

**Issue by abl** [edisonchee/slimbot#4]
Somewhat counterintuitively, reply_markup expects a JSON string:

```
// Works
  let optionalParams = {
    reply_markup: JSON.stringify({
      keyboard: [
        [
          {text: '/lock'},
        ],
        [
          {text: '/unlock'},
        ]
      ]
    })
  };

// Doesn't work
  let optionalParams = {
    reply_markup: {
      keyboard: [
        [
          {text: '/lock'},
        ],
        [
          {text: '/unlock'},
        ]
      ]
    }
  };
```

Might be worth checking to see if `reply_markup` is a string, and if not, `stringify`ing it in sendMessage?

**Comment by edisonchee** [comment]
Hi @abl! Thanks for pointing this out. I just realised the example in the readme is inaccurate.

I originally decided against adding such a feature as I wanted the lib to be as thin as possible. Moreover, the [#sendMessage method](https://core.telegram.org/bots/api#sendmessage) already specifies _reply_markup_ to require a JSON-serialized object.

Nonetheless, feel free to work on it and make a PR when you're done.

**Comment by edisonchee** [comment]
Closing this issue until further updates.
