### ISSUE TITLE
Is this library requires node v13?

### ISSUE THREAD

**Issue by yofriadi** [edisonchee/slimbot#41]
I want to use it in cloud functions which currently not support node v13

**Comment by edisonchee** [comment]
Hi @yofriadi, the lib is tested on  Node `10.16.0` and `12.10.0` as well.

**Comment by yofriadi** [comment]
but in package.json it targets node 13, I cant install it??

**Comment by edisonchee** [comment]
@yofriadi you're right, it's my mistake. Sorry about that. I was not aware that setting the node version in engines will prevent people from installing it. I've fixed it in c9ca8b0afe1b396cc4292588405e0c425a98aba7 and published `4.6.3` on npm. Try updating and let me know if you can install.
