### ISSUE TITLE
package.json "engine" constraint breaks yarn 

### ISSUE THREAD

**Issue by nahanil** [edisonchee/slimbot#42]
Heya

Just noticed that yarn will die with the following when trying to install with node 12/13 as [^10.x.x](https://github.com/edisonchee/slimbot/blob/c9ca8b0afe1b396cc4292588405e0c425a98aba7/package.json#L19) only matches major version 10. `npm` doesn't seem to care.
```
error slimbot@4.6.3: The engine "node" is incompatible with this module. Expected version "^10.16.0". Got "13.10.1"
error Found incompatible module.
```

I think `>=10.x.x` could do the business

**Comment by edisonchee** [comment]
Merged :) Thanks a lot @nahanil
