### ISSUE TITLE
it supports inline_keyboard but not keyboard

### ISSUE THREAD

**Issue by jimmyranson229** [edisonchee/slimbot#48]
callback_query is only supporting inline_keyboard but not keyboard. please help

**Comment by dilutedh2o** [comment]
Are there any updates on this?

**Comment by edisonchee** [comment]
@jimmyranson229 @dilutedh2o sorry I'm not too sure what the request is here. Could either of you show an example of what you're trying to achieve?

**Comment by edisonchee** [comment]
Closed until further response or if anybody else has issues with this.
