### ISSUE TITLE
setWebhook discards url parameter?

### ISSUE THREAD

**Issue by abl** [edisonchee/slimbot#5]
https://github.com/edisonchee/slimbot/blob/e173be2e4a1fedec17a5e80dd52835c7279c8441/src/telegram.js#L56

You can see that url isn't propagated forward - which means the correct usage of setWebhook would be:

`slimbot.setWebhook(null, {'url':MY_URL});`

instead of

`slimbot.setWebhook(MY_URL);`

which actually deletes any webhooks that are set up.

**Comment by edisonchee** [comment]
Thanks @abl for the catch!
