### ISSUE TITLE
Error: Please provide a Telegram Bot Token when instantiating

### ISSUE THREAD

**Issue by Joni4Games** [edisonchee/slimbot#7]
So.. I've added the first sample code. I've requested the Telegram Bot API Key via the BotFather and added it in there. Now I get the error:
`Error: Please provide a Telegram Bot Token when instantiating`

My Key looks like: 

> 123456789:Ab1Cd2Ef3Gh4Ij5Kl6Mn7Op8Qr9

I'm using Node `v8.1.2`

Nothing found in the web
![1](https://user-images.githubusercontent.com/20246294/27309148-c0256b28-5552-11e7-8dbe-23a60b5dde66.PNG)
![2](https://user-images.githubusercontent.com/20246294/27309203-fb6b6606-5552-11e7-9f9b-6bcc1f1f23c1.PNG)
PS: Anyway you whole project looks good

**Comment by Joni4Games** [comment]
Worked by simply removing the "process.env".
![3](https://user-images.githubusercontent.com/20246294/27325874-17cd0e7e-55aa-11e7-860c-702282bf54e1.PNG)

**Comment by d-a-w** [comment]
Worked by removing the "process.env". Thank u @Joni4Games

**Comment by edisonchee** [comment]
Sorry for not following up on this. `process.env` is for environment variables that are loaded into your shell, usually found in `~/.profile`.

An example inside your `~/.profile` would be:
```bash
export TELEGRAM_BOT_TOKEN='token string'
```

And you'd use it in Node like this:
```js
const token = process.env['TELEGRAM_BOT_TOKEN']
```
